// <auto-generated />
namespace Thinktecture.IdentityServer.Core.Repositories.Migrations.SqlServer
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddScopeToIdentityProvider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddScopeToIdentityProvider));
        
        string IMigrationMetadata.Id
        {
            get { return "201412172246367_AddScopeToIdentityProvider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
